### ISSUE TITLE
Wrong generating of requests hex strings

### ISSUE THREAD

**Issue by Jusufs** [zocker-160/xcom-protocol#1]
Hi,
Sorry, but your serial communication via Xcom232i doesn't work correctly.
It generates not correct hex strings as request.
Therefore no answer from 232i communication.

I'm from Slovakia SK and can you support with my results.
This would be fine to get working. 
Lot of users have 232i adapter.

**Comment by zocker-160** [comment]
Yes I know, this protocol implementation is lacking as stated in the readme and the overall code quality is quite bad.

If you happen to know where in the implementation I am doing something wrong, let me know, I can look into it.

Contributions via PR are also welcome as I wrote this in my spare time and there is no guarantee at all that it will work correctly.

EDIT: I am using this code personally for feeding data into Home Assistant and it works well, so this is why no update has been happening, as it is good enough for my personal use case.

**Comment by zocker-160** [comment]
I have done an almost complete rewrite of the protocol, if this issue still persists then please create a new issue, but also please provide more information about the issue and what is wrong, because "does not work" is not enough.
