### ISSUE TITLE
TYPE_LONG_ENUM needed

### ISSUE THREAD

**Issue by spinozarabel** [zocker-160/xcom-protocol#8]
Greetings,
First of, thank you for this work.
I am trying to set some parameters that need type LONG_ENUM. I tried to do it myself but I keep getting error DATA TOO SHORT or some such thing. SInce you developed this package it may be trivial for you to add? So this is a request.

Thanks and regards,  Madhu

**Comment by zocker-160** [comment]
Just to clarify, you get `DATA_TOO_SMALL` error when using `TYPE_SHORT_ENUM` and when using `TYPE_LONG_ENUM` you get an `Unknown datatype` error correct?

**Comment by zocker-160** [comment]
I just pushed a new version to PyPi which adds the remaining 3 data types to the Datapoint packer / unpacker.

Let me know if that fixes the issue for you.

**Comment by spinozarabel** [comment]
Hi,
Thanks for the quick response and code push. I really appreciate it. It works. Please close this issue.

Have a great day!
